services:
  bookmark-searcher-frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: server
    ports:
      - "5173:80"
    environment:
      - API_BASE_URL=http://bookmark-searcher-backend:8000
    depends_on:
      - bookmark-searcher-backend
